services:
  postgres:
    image: postgres:16-alpine
    container_name: jwt-security
    environment:
      POSTGRES_DB: jwt-security
      POSTGRES_USER: akt
      POSTGRES_PASSWORD: akt
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: