spring.application.name=jwt

spring.datasource.url= jdbc:postgresql://localhost:5432/jwt-security
spring.datasource.driver-class-name= org.postgresql.Driver
spring.datasource.username= akt
spring.datasource.password= akt

spring.jpa.hibernate.ddl-auto= create-drop
spring.jpa.show-sql= true
spring.jpa.open-in-view= false
spring.jpa.properties.hibernate.format_sql= true

jwt.secret-key= Q2yLpFA57DYqIaiKOHBJkx22SOhfXcbr6BvjVAwfU/eiJmi8T6iwQ01LE3v6cjz3uayKCRPUtY3SYqmGnH1Hiw==
jwt.secret-key-expiration= 15m
