spring.application.name=jwt

spring.datasource.url= jdbc:postgresql://localhost:5432/jwt-security
spring.datasource.driver-class-name= org.postgresql.Driver
spring.datasource.username= akt
spring.datasource.password= akt

spring.jpa.hibernate.ddl-auto= create-drop
spring.jpa.show-sql= true
spring.jpa.open-in-view= false
spring.jpa.properties.hibernate.format_sql= true

jwt.secret-key= pzZYE9PGHaDHkUSO2o2ucP/fXtg6OgYGXHCPxx9gqkyVZLQDVxQP0C18No0y1CzB66illm8RT4i0p33BD4N8qw==
jwt.secret-key-expiration= 15m
jwt.refresh-token-expiration= 7d
